import{a as m,S as h,i as l}from"./assets/vendor-5401a4b0.js";(function(){const r=document.createElement("link").relList;if(r&&r.supports&&r.supports("modulepreload"))return;for(const t of document.querySelectorAll('link[rel="modulepreload"]'))c(t);new MutationObserver(t=>{for(const i of t)if(i.type==="childList")for(const d of i.addedNodes)d.tagName==="LINK"&&d.rel==="modulepreload"&&c(d)}).observe(document,{childList:!0,subtree:!0});function s(t){const i={};return t.integrity&&(i.integrity=t.integrity),t.referrerPolicy&&(i.referrerPolicy=t.referrerPolicy),t.crossOrigin==="use-credentials"?i.credentials="include":t.crossOrigin==="anonymous"?i.credentials="omit":i.credentials="same-origin",i}function c(t){if(t.ep)return;t.ep=!0;const i=s(t);fetch(t.href,i)}})();async function u(o){const r="42127236-8bfdbbfbeed8a2dadaca720e8",s="/api/";return m.defaults.baseURL="https://pixabay.com",(await m.get(s,{params:{key:r,q:o,image_type:"photo",orientation:"horisontal",safesearch:!0,per_page:15,page:n}})).data}function p(o){return o.hits.map(s=>`<li class="gallery-item">
          <a href="${s.largeImageURL}"><img src="${s.webformatURL}" alt="${s.tags}" class="gallery-image" /></a>
          <div class="gallery-wrap">
          <p><b>Likes</b><br />${s.likes}</p>
          <p><b>Views</b><br />${s.views}</p>
          <p><b>Comments</b><br />${s.comments}</p>
          <p><b>Downloads</b><br />${s.downloads}</p>
          </div>
        </li>`).join("")}let n;const e={formRef:document.querySelector(".form"),formInputRef:document.querySelector(".form-input"),galleryRef:document.querySelector(".gallery"),loaderRef:document.querySelector(".loader"),loadMoreBtnRef:document.querySelector(".load-more-btn"),upBtnRef:document.querySelector(".up-btn")},g={captionDelay:250,captionsData:"alt"};let a;const f=new h(".gallery a",g);e.formRef.addEventListener("submit",o=>{n=1,o.preventDefault(),e.galleryRef.innerHTML="",e.loaderRef.classList.remove("hide"),e.loadMoreBtnRef.classList.add("hide"),a=e.formInputRef.value,a.trim()===""?(e.formRef.reset(),e.loaderRef.classList.add("hide")):u(a).then(r=>{e.formRef.reset(),r.totalHits>15&&(e.loadMoreBtnRef.classList.remove("hide"),e.upBtnRef.classList.remove("hide")),r.hits.length===0&&l.error({message:"Sorry, there are no images matching your search query. Please, try again!",messageColor:"white",backgroundColor:"red",position:"topRight",maxWidth:432}),e.galleryRef.innerHTML=p(r),f.on("show.simplelightbox"),f.refresh()}).catch(r=>l.error({message:r.message,position:"topRight",maxWidth:432})).finally(()=>{e.loaderRef.classList.add("hide")})});e.loadMoreBtnRef.addEventListener("click",()=>{e.loaderRef.classList.remove("hide"),e.loadMoreBtnRef.classList.add("hide"),n++,u(a).then(o=>{o.totalHits>=n*15?(e.loadMoreBtnRef.classList.remove("hide"),e.galleryRef.insertAdjacentHTML("beforeend",p(o))):l.info({message:"We're sorry, but you've reached the end of search results.",position:"topRight"}),f.refresh();const r=document.querySelector(".gallery-item").getBoundingClientRect();window.scrollBy({top:r.height*2,behavior:"smooth"})}).catch(o=>l.error({message:o.message,position:"topRight",maxWidth:432})).finally(()=>{e.loaderRef.classList.add("hide")})});e.upBtnRef.addEventListener("click",()=>{window.scrollTo({top:0,behavior:"smooth"})});
//# sourceMappingURL=commonHelpers.js.map
